export const COUNTRY_CODES: any = {
    'US': 'United States',
    'CN': 'China',
    'IN': 'India',
    'BR': 'Brazil',
    'NG': 'Nigeria',
    'RU': 'Russia',
    'ID': 'Indonesia',
    'PK': 'Pakistan',
    'BD': 'Bangladesh',
    'JP': 'Japan',
    'MX': 'Mexico',
    'PH': 'Philippines',
    'VN': 'Vietnam',
    'ET': 'Ethiopia',
    'EG': 'Egypt',
    'CD': 'Democratic Republic of the Congo',
    'TZ': 'Tanzania',
    'PL': 'Poland',
    'CA': 'Canada',
    'UG': 'Uganda',
    'KE': 'Kenya',
    'DZ': 'Algeria',
    'SD': 'Sudan',
    'MG': 'Madagascar',
    'AO': 'Angola',
}